# -*- coding: utf-8 -*-
"""Quantum Circuit Coding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E6KBHDsB9iv6adb3CGs-lKwd3MaGDY0z
"""

!pip install qiskit
from qiskit import *
!pip install qiskit-aer

#Creates a 3 qubit circuit
circ = QuantumCircuit(3)
# Creates an H gate on quibit 0 and puts it in superpoisiton 0, and 1 50% respectively
circ.h(0)
#Creates a CX (Controlled-NOT gate) on quibit 1 (Control= 0 Target quibit= 1) IF quibit 0 is 1 flip quibit 1, thus entangling quibits 0 and 1,
circ.cx(0,1)
# If quibit 0 is 1 flip quibit 2 (q0, q1, and q2 all become entangled)
circ.cx(0,2)
circ.draw()
#Creates a GHZ state (|000⟩ + |111⟩) / √2 Either all three are 0 or all three are 1. You don’t know which until you measure, but once you measure one → you instantly know the others.

from qiskit import QuantumCircuit
from qiskit_aer import AerSimulator

# Create GHZ circuit
circ = QuantumCircuit(3)
circ.h(0)
circ.cx(0, 1)
circ.cx(0, 2)
circ.measure_all()

# Create simulator
sim = AerSimulator()

# Run circuit
job = sim.run(circ, shots=1024)
result = job.result()

# Get results
counts = result.get_counts()
print(counts)

circ = QuantumCircuit(1)
circ.h(0)
circ.z(0)
circ.h(0)
circ.measure_all()
circ.draw()

circ = QuantumCircuit(11)
circ.h(0)
circ.cx(0,1)
circ.cx(0,1)
circ.cz(0,1)
circ.measure_all()
circ.draw()